import type { Post, Club, Event, MarketplaceListing, Job, Campaign, Perk, UserProfile } from "@/types"

export const mockPosts: Post[] = [
  {
    id: "post-1",
    authorId: "user-1",
    authorName: "Sarah Kimani",
    authorPhotoURL: "/african-woman-professional.jpg",
    content: "Excited to announce that our batch of 2012 is organizing a reunion next month! Who's in? 🎉",
    imageURL: "/kenyan-high-school-students-in-uniforms-classroom-.jpg",
    likes: ["user-2", "user-3", "user-4"],
    commentsCount: 8,
    createdAt: "2024-11-20T10:30:00Z",
  },
  {
    id: "post-2",
    authorId: "user-2",
    authorName: "David Ochieng",
    authorPhotoURL: "/african-businessman.png",
    content:
      "Just visited Light Academy last week and was amazed by the new science labs! The school has really grown. Proud to be an alumnus.",
    imageURL: "/african-students-school-uniforms-science-laborator.jpg",
    likes: ["user-1", "user-3"],
    commentsCount: 5,
    createdAt: "2024-11-19T14:00:00Z",
  },
  {
    id: "post-3",
    authorId: "user-3",
    authorName: "Grace Wanjiku",
    authorPhotoURL: "/african-woman-teacher.jpg",
    content:
      "Looking for mentors for our upcoming career day at Light Academy. If you're interested in speaking to current students about your profession, please reach out!",
    imageURL: "/kenyan-students-school-uniforms-assembly-hall-inte.jpg",
    likes: ["user-1", "user-2", "user-4", "user-5"],
    commentsCount: 12,
    createdAt: "2024-11-18T09:15:00Z",
  },
  {
    id: "post-4",
    authorId: "user-4",
    authorName: "James Mutua",
    authorPhotoURL: "/african-man-student.jpg",
    content:
      "Throwback to our graduation day! Can't believe it's been a year already. Missing the Light Academy family.",
    imageURL: "/african-students-graduation-ceremony-school-unifor.jpg",
    likes: ["user-1", "user-2", "user-3"],
    commentsCount: 15,
    createdAt: "2024-11-17T11:00:00Z",
  },
  {
    id: "post-5",
    authorId: "user-5",
    authorName: "Peter Njoroge",
    authorPhotoURL: "/african-man-engineer.jpg",
    content:
      "Amazing to see the current students winning the national science competition! Light Academy continues to excel in academics.",
    imageURL: "/kenyan-students-school-uniforms-science-competitio.jpg",
    likes: ["user-1", "user-2", "user-3", "user-4"],
    commentsCount: 20,
    createdAt: "2024-11-16T09:30:00Z",
  },
]

export const mockClubs: Club[] = [
  {
    id: "club-1",
    name: "Tech Innovators",
    description: "For alumni in technology and software development",
    icon: "laptop",
    memberCount: 245,
    category: "professional",
  },
  {
    id: "club-2",
    name: "Healthcare Heroes",
    description: "Doctors, nurses, and healthcare professionals",
    icon: "heart-pulse",
    memberCount: 189,
    category: "professional",
  },
  {
    id: "club-3",
    name: "Entrepreneurs Circle",
    description: "Business owners and startup founders",
    icon: "rocket",
    memberCount: 312,
    category: "professional",
  },
  {
    id: "club-4",
    name: "Book Club",
    description: "Monthly reads and literary discussions",
    icon: "book-open",
    memberCount: 156,
    category: "interest",
  },
  {
    id: "club-5",
    name: "Sports & Fitness",
    description: "Stay active with fellow alumni",
    icon: "dumbbell",
    memberCount: 278,
    category: "interest",
  },
  {
    id: "club-6",
    name: "Creative Arts",
    description: "Artists, musicians, and creatives",
    icon: "palette",
    memberCount: 134,
    category: "interest",
  },
  {
    id: "club-7",
    name: "Nairobi Chapter",
    description: "Alumni based in Nairobi",
    icon: "map-pin",
    memberCount: 523,
    category: "regional",
  },
  {
    id: "club-8",
    name: "Class of 2015",
    description: "Stay connected with your batchmates",
    icon: "graduation-cap",
    memberCount: 89,
    category: "batch",
  },
]

export const mockEvents: Event[] = [
  {
    id: "event-1",
    title: "Annual Alumni Gala 2024",
    description: "Join us for an evening of celebration, networking, and giving back.",
    date: "2024-12-15",
    time: "18:00",
    location: "Serena Hotel, Nairobi",
    isVirtual: false,
    registeredCount: 156,
    imageURL: "/elegant-gala-dinner.png",
  },
  {
    id: "event-2",
    title: "Tech Career Workshop",
    description: "Learn about emerging trends in technology from industry leaders.",
    date: "2024-12-05",
    time: "14:00",
    location: "Virtual Event",
    isVirtual: true,
    registeredCount: 89,
  },
  {
    id: "event-3",
    title: "Class of 2010 Reunion",
    description: "Reconnect with your classmates after 14 years!",
    date: "2024-12-20",
    time: "16:00",
    location: "Light Academy Campus",
    isVirtual: false,
    registeredCount: 45,
  },
]

export const mockListings: MarketplaceListing[] = [
  {
    id: "listing-1",
    sellerId: "user-5",
    sellerName: "Peter Njoroge",
    title: "MacBook Pro 2022 - Excellent Condition",
    description: "Used for 1 year, comes with original charger and box.",
    price: 150000,
    category: "Electronics",
    imageURL: "/macbook-pro-laptop.png",
    status: "active",
    createdAt: "2024-11-15T10:00:00Z",
  },
  {
    id: "listing-2",
    sellerId: "user-6",
    sellerName: "Mary Akinyi",
    title: "Professional Photography Services",
    description: "Events, portraits, and corporate photography. Alumni discount available!",
    price: 25000,
    category: "Services",
    imageURL: "/professional-camera-photography.jpg",
    status: "active",
    createdAt: "2024-11-14T15:30:00Z",
  },
]

export const mockJobs: Job[] = [
  {
    id: "job-1",
    posterId: "user-7",
    posterName: "James Kamau",
    company: "Safaricom PLC",
    title: "Senior Software Developer",
    description: "Looking for experienced developers to join our mobile money team.",
    location: "Nairobi, Kenya",
    type: "full-time",
    salary: "KES 200,000 - 350,000",
    createdAt: "2024-11-18T09:00:00Z",
  },
  {
    id: "job-2",
    posterId: "user-8",
    posterName: "Elizabeth Muthoni",
    company: "KCB Bank",
    title: "Marketing Manager",
    description: "Lead our digital marketing initiatives across East Africa.",
    location: "Nairobi, Kenya",
    type: "full-time",
    salary: "KES 250,000 - 400,000",
    createdAt: "2024-11-17T14:00:00Z",
  },
]

export const mockCampaigns: Campaign[] = [
  {
    id: "campaign-1",
    title: "New Library Building Fund",
    description: "Help us build a state-of-the-art library for current students.",
    goal: 5000000,
    raised: 3250000,
    endDate: "2025-03-31",
    imageURL: "/modern-library-building-in-kenyan-school.jpg",
  },
  {
    id: "campaign-2",
    title: "Scholarship Fund 2024",
    description: "Support deserving students who cannot afford school fees.",
    goal: 2000000,
    raised: 1750000,
    endDate: "2024-12-31",
    imageURL: "/happy-african-students-in-classroom-kenya.jpg",
  },
  {
    id: "campaign-3",
    title: "Sports Equipment Drive",
    description: "Upgrade sports facilities and equipment for student athletes.",
    goal: 1500000,
    raised: 450000,
    endDate: "2025-06-30",
    imageURL: "/school-sports-equipment-football-basketball.jpg",
  },
]

export const mockPerks: Perk[] = [
  {
    id: "perk-5",
    business: "Pop Network Africa",
    owner: "Light Alumni Partner",
    description: "Precision and relevance marketing services for businesses across Africa",
    discount: "25% off all marketing packages",
    category: "Marketing",
    logoURL: "/pop-network-logo.png",
    website: "https://www.popnetwork.africa/",
  },
  {
    id: "perk-1",
    business: "Kamau's Auto Service",
    owner: "Peter Kamau (Class of 2008)",
    description: "Complete car servicing and repairs",
    discount: "15% off all services",
    category: "Automotive",
    logoURL: "/auto-repair-logo.jpg",
  },
  {
    id: "perk-2",
    business: "Wanjiku Law Firm",
    owner: "Grace Wanjiku (Class of 2005)",
    description: "Legal services for individuals and businesses",
    discount: "Free initial consultation",
    category: "Legal",
    logoURL: "/law-firm-logo.png",
  },
  {
    id: "perk-3",
    business: "Ochieng Photography",
    owner: "David Ochieng (Class of 2012)",
    description: "Professional photography for all occasions",
    discount: "20% off wedding packages",
    category: "Photography",
    logoURL: "/photography-studio-logo.png",
  },
  {
    id: "perk-4",
    business: "TechHub Coworking",
    owner: "John Mwangi (Class of 2015)",
    description: "Modern coworking spaces in Nairobi",
    discount: "First month free",
    category: "Business Services",
    logoURL: "/coworking-space-logo.jpg",
  },
]

export const mockUsers: UserProfile[] = [
  {
    id: "user-1",
    email: "sarah.kimani@email.com",
    displayName: "Sarah Kimani",
    photoURL: "/african-woman-professional.jpg",
    graduationYear: 2012,
    campus: "Light Academy Nairobi",
    jobTitle: "Product Manager",
    company: "Google",
    location: "San Francisco, USA",
    country: "USA",
    city: "San Francisco",
    status: "working",
    membershipTier: "platinum",
    createdAt: "2022-03-15T10:00:00Z",
    updatedAt: "2024-10-01T15:30:00Z",
  },
  {
    id: "user-2",
    email: "david.ochieng@email.com",
    displayName: "David Ochieng",
    photoURL: "/african-businessman.png",
    graduationYear: 2010,
    campus: "Light Academy Mombasa",
    jobTitle: "CEO",
    company: "Ochieng Enterprises",
    location: "Nairobi, Kenya",
    country: "Kenya",
    city: "Nairobi",
    status: "working",
    membershipTier: "gold",
    createdAt: "2021-06-20T08:00:00Z",
    updatedAt: "2024-09-15T12:00:00Z",
  },
  {
    id: "user-3",
    email: "grace.wanjiku@email.com",
    displayName: "Grace Wanjiku",
    photoURL: "/african-woman-teacher.jpg",
    graduationYear: 2005,
    campus: "Light Academy Nairobi",
    jobTitle: "Senior Partner",
    company: "Wanjiku Law Firm",
    location: "Nairobi, Kenya",
    country: "Kenya",
    city: "Nairobi",
    status: "working",
    membershipTier: "platinum",
    createdAt: "2020-01-10T09:00:00Z",
    updatedAt: "2024-11-01T10:00:00Z",
  },
  {
    id: "user-4",
    email: "james.mutua@email.com",
    displayName: "James Mutua",
    photoURL: "/african-man-student.jpg",
    graduationYear: 2023,
    campus: "Light Academy Nairobi",
    location: "Nairobi, Kenya",
    country: "Kenya",
    city: "Nairobi",
    status: "studying",
    membershipTier: "free",
    createdAt: "2024-02-15T14:00:00Z",
    updatedAt: "2024-11-10T16:00:00Z",
  },
  {
    id: "user-5",
    email: "peter.njoroge@email.com",
    displayName: "Peter Njoroge",
    photoURL: "/african-man-engineer.jpg",
    graduationYear: 2008,
    campus: "Light Academy Nairobi",
    jobTitle: "CTO",
    company: "Tech Solutions Ltd",
    location: "London, UK",
    country: "UK",
    city: "London",
    status: "working",
    membershipTier: "gold",
    createdAt: "2019-08-20T11:00:00Z",
    updatedAt: "2024-10-20T09:00:00Z",
  },
]

interface LocationCluster {
  id: string
  name: string
  location: string
  country: string
  region: "africa" | "europe" | "americas" | "asia"
  description: string
  memberCount: number
  imageUrl: string
  coordinates: { lat: number; lng: number }
  chapterLead?: string
  contactEmail?: string
  nextMeetup?: string
}

export const locationClusters: LocationCluster[] = [
  {
    id: "cluster-nairobi",
    name: "Nairobi Chapter",
    location: "Nairobi",
    country: "Kenya",
    region: "africa",
    description:
      "The largest alumni community in East Africa. Regular meetups, networking events, and mentorship programs.",
    memberCount: 523,
    imageUrl: "/nairobi-kenya-skyline-cityscape.jpg",
    coordinates: { lat: -1.2921, lng: 36.8219 },
    chapterLead: "Sarah Kimani",
    contactEmail: "nairobi@lightalumni.org",
    nextMeetup: "2024-12-15",
  },
  {
    id: "cluster-mombasa",
    name: "Mombasa Chapter",
    location: "Mombasa",
    country: "Kenya",
    region: "africa",
    description: "Coastal alumni community connecting professionals along the Kenyan coast and beyond.",
    memberCount: 187,
    imageUrl: "/mombasa-kenya-beach-coastal-city.jpg",
    coordinates: { lat: -4.0435, lng: 39.6682 },
    chapterLead: "David Ochieng",
    contactEmail: "mombasa@lightalumni.org",
    nextMeetup: "2024-12-20",
  },
  {
    id: "cluster-uk",
    name: "United Kingdom Chapter",
    location: "London",
    country: "United Kingdom",
    region: "europe",
    description: "Connect with fellow alumni across England, Scotland, Wales, and Northern Ireland.",
    memberCount: 156,
    imageUrl: "/london-uk-big-ben-thames-river.jpg",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    chapterLead: "Peter Njoroge",
    contactEmail: "uk@lightalumni.org",
    nextMeetup: "2024-12-18",
  },
  {
    id: "cluster-usa",
    name: "United States Chapter",
    location: "New York",
    country: "United States",
    region: "americas",
    description: "Alumni network spanning coast to coast across America. Active chapters in major cities.",
    memberCount: 234,
    imageUrl: "/new-york-city-skyline-manhattan.jpg",
    coordinates: { lat: 40.7128, lng: -74.006 },
    chapterLead: "Grace Wanjiku",
    contactEmail: "usa@lightalumni.org",
    nextMeetup: "2024-12-22",
  },
  {
    id: "cluster-europe",
    name: "Europe Chapter",
    location: "Berlin",
    country: "Germany",
    region: "europe",
    description: "Pan-European alumni network covering Germany, France, Netherlands, and more.",
    memberCount: 98,
    imageUrl: "/berlin-germany-brandenburg-gate.jpg",
    coordinates: { lat: 52.52, lng: 13.405 },
    chapterLead: "James Mutua",
    contactEmail: "europe@lightalumni.org",
    nextMeetup: "2024-12-25",
  },
  {
    id: "cluster-malaysia",
    name: "Malaysia Chapter",
    location: "Kuala Lumpur",
    country: "Malaysia",
    region: "asia",
    description: "Growing community in Southeast Asia with strong ties to the Kenyan diaspora.",
    memberCount: 67,
    imageUrl: "/kuala-lumpur-malaysia-petronas-towers.jpg",
    coordinates: { lat: 3.139, lng: 101.6869 },
    chapterLead: "Mary Akinyi",
    contactEmail: "malaysia@lightalumni.org",
    nextMeetup: "2025-01-05",
  },
]
